= My First Blog
Siddhesh Rane
2017-06-06 02:22
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, jekyll


I was never really into blogging. Even today it's not the conventional aspects of blogging that has got me started with one.
In this post I will explore why I chose a static blog over the obvious choice of a Wordpress one.

=== Me and Blogs 

[quote]
____

Books are a man's best friend. Mine are blogs. 
____

I used to read a lot of technical blogs that I came across through google searches. Once I landed on a blog and liked it I would also read related posts. Blogs were a very valuable source of information, much more so than books. They were convenient in that they were concise, to the point and conveyed information in simple terms. They introduced you to new technologies, people, current trends and aspects of software development beyond coding.

In short I enjoyed _reading_ blogs, but that didn't get me into _writing_ one.
So what was it that I wanted?

=== A Website!

A blog couldn't excite me as much as a website did. A website could look as you wanted, have pages and features you could think of.
I wanted a website to be my profile, business card, CV, a documentation of my projects and everything I felt like putting on the web, but in a differentiated way, under a resource identifiable with my name. I wanted a personal website.

To have a website you need two things: a domain name and a hosting service. Both options cost money on a regular basis, which however small was not suitable for a student like me who had no web development skills nor the time for regular maintenance.
I had briefly considered creating a Wordpress blog because that was the easy route. But I didnt get a website URL with my name in it. So I dropped the whole plan.

The idea of a website went from the back of my head to the brink of oblivion.

=== From Oblivion to Obsession

The idea hadn't died, just remained dormant. It resurfaced when I read about https://pages.github.com[Github Pages]. Github Pages had two very important things at offer

* It provides a cdn like hosting service where you can publish an entire static website. Static doesn't mean plain boring wiki pages. You can have completly interactive HTML5 webapps. Just no server side code.

* The default URL for your website is username.github.io which in my case becomes 
https://SiddheshRane.github.io[SiddheshRane.github.io] 
This was crucial. The URL had my exact name in it. It wasn't https://github.com/SiddheshRane[github.com/SiddheshRane] that would make my website a mere page under github nor was it some ww2.0xsiddhesh-rane3.unkownhost.com. 
The URL has the perfect structure. Begins with my name, followed by github which is cool and ends in `.io` which is even cooler. There is something very _develeperish_ about `.io`

And then there were all those awesome gh-pages that other github projects had, it all got me very excited and really inspired. 

So basically I chose Github Pages and a static website was the consequence.

=== From Website to Blog?

Github Pages introduced me to link:https://jekyllrb.com[Jekyll], a static site generator that is blog aware. Jekyll captivated me because their website is simply beautiful and so concise. While I was reading their documentation I was adoring that dark theme, that easy on the eyes typography and those banners conveying important information, like in asciidoc.

Jekyll's eye candy made me try it out. And since their tutorial was blog oriented I ended up going the same route.
You never know there is something you might like doing until you try it. Jekyll was that thing. It got me into blogging.

=== An Ironical Twist

If you scroll down to the bottom of this page you'll notice that the site is baked with JBake. This is *not* a Jekyll generated site! JBake is an alternative static site generator that is also blog aware. Why I ditched Jekyll to go with something else is for another link:why-jbake.html[blog post].
